language: java

jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - master
    - development
    -SarahPatrick
    - ScottJones
    - PaytonSuiter

after_success:
  - mvn clean test jacoco:report coveralls:report
