language: java

jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - development
    - SarahPatrick
    - ScottJones
    - Payton-Suiter
    - MichaelSalinas
    - BeccaCario

after_success:
  - mvn clean test jacoco:report coveralls:report
