language: java

jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - master
    - development
    -SarahPatrick
    - ScottJones
    - Payton-Suiter
    -MichaelSalinas
    - Becca Cario

after_success:
  - mvn clean test jacoco:report coveralls:report
